Housekeeping & exposing get_schema_and_id
gklijs/schema_registry_converter pull request #93
Opened 2023-10-12 10:32 UTC by Licenser

This contains 4 improvements:

1) implement the code improvements suggested by `cargo clippy`
2) clean up the SubjectNameStrategy enum to:
  a) be more along the lines of idiomatic rust code
  b) remove unnecessary boxes
3) expose the `get_schema_and_id` function for the encoder
4) fix the function signature for `EasyAvroEncoder::encode` to allow non static strings as keys

2023-10-12 17:55 UTC, gklijs commented
Thanks a lot. It's funny how introducing the boxes was suggested by Clippy in the [past](git@github.com:tremor-rs/schema_registry_converter.git).
I enabled the test to run. Would you happen to have the time to fix the tests? Otherwise, I can pick this over.
As this would be a breaking change, it would make the next release a 4.0.0 one, which is fine.
Would you have further suggestions, specifically do you think [splitting the crate](https://github.com/gklijs/schema_registry_converter/discussions/91) would be beneficial?

2023-10-12 18:10 UTC, gklijs requested changes
Looks good, some additional small changes are needed so the tests compile again.

2023-10-12 19:09 UTC, Licenser commented
uff sorry about that, should be fixed, even so the `blocking` tests don't run when I run all tests together, just when I run them separately I suspect that's related to the mockio library

2023-10-12 20:58 UTC, gklijs commented
To run all the tests, you need both the `--all-features` flag, and the `--test-threads=1` flag to work nicely with mockio. No point taken, I'm very glad you took the work to create a pr.

2023-10-12 21:06 UTC, gklijs commented
Some doctests still need to be adopted. There is no rush.

2023-10-13 12:04 UTC, Licenser commented
idk what it is but locally `cargo test  --all-features -- --test-threads=1` still fails on the blocking tests if they are run together. I suspect it has to do with running them on a many-core machine

but in the CI they work:
```
running 9 tests
test blocking::avro_tests::test1_topic_name_strategy_with_schema ... ok
test blocking::avro_tests::test2_record_name_strategy_with_schema ... ok
test blocking::avro_tests::test3_topic_record_name_strategy_with_schema ... ok
test blocking::avro_tests::test4_topic_name_strategy_schema_now_available ... ok
test blocking::avro_tests::test5_record_name_strategy_schema_now_available ... ok
test blocking::avro_tests::test6_topic_record_name_strategy_schema_now_available ... ok
test blocking::avro_tests::test7_test_avro_from_java_test_app ... ok
test blocking::proto_tests::test1_test_proto_from_java_test_app ... ok
test blocking::proto_tests::test2_test_google_proto_from_java_test_app ... ok
```

just means I can't run the whole suite locally but I'll run --docs separately to work the doc tests out :)

2023-10-13 13:26 UTC, gklijs approved these changes
Again, thanks a lot.
I might have some time to include some of the open tickets and release 4.0.0 soon.

2023-10-13 13:27 UTC, merged